### ISSUE TITLE
Uncaught Exceptions?

### ISSUE THREAD

**Issue by causefx** [kaysond/deluge-php#1]
my code works when the values are correct but if it intentionally try with bad credentials I get uncaught exceptions:

```
try {
					
	$deluge = new deluge($GLOBALS['delugeURL'], decrypt($GLOBALS['delugePassword']));
	return $deluge->getTorrents(null, 'comment, download_payload_rate, eta, hash, is_finished, is_seed, message, name, paused, progress, queue, state, total_size, upload_payload_rate');
} catch (Excecption $e) {
	return $e->getMessage();
}
```

Errors:

```
<br />
<b>Fatal error</b>:  Uncaught Exception: Could not log in due to curl error (no. 7): Failed to connect to usenet.home.lab port 8113: Connection refused in C:\nginx\html\Organizr\api\functions\deluge.class.php:563
Stack trace:
#0 C:\nginx\html\Organizr\api\functions\deluge.class.php(30): deluge-&gt;makeRequest('auth.login', Array)
#1 C:\nginx\html\Organizr\api\functions\homepage-connect-functions.php(1775): deluge-&gt;__construct('http://usenet.h...', 'xxxxxxxxx')
#2 C:\nginx\html\Organizr\api\index.php(333): testAPIConnection(Array)
#3 {main}

Next Exception: Failed to initiate deluge api in C:\nginx\html\Organizr\api\functions\deluge.class.php:35
Stack trace:
#0 C:\nginx\html\Organizr\api\functions\homepage-connect-functions.php(1775): deluge-&gt;__construct('http://usenet.h...', 'xxxxxxxxx')
#1 C:\nginx\html\Organizr\api\index.php(333): testAPIConnection(Array)
#2 {main}
  thrown in <b>C:\nginx\html\Organizr\api\functions\deluge.class.php</b> on line <b>35</b><br />

```

**Comment by kaysond** [comment]
If you check the readme, you'll see that this is by design. Any failure throws an exception, including login failures, as indicated in the error message. It's definitely not the most robust error handling, but it works.

However, it looks like you have a different issue. When I pass bad credentials, I get ` Uncaught Exception: Login failed in /var/www/deluge.class.php:28`, which is what I expect. In your case, it's not able to make a connection at all, hence the curl error.

**Comment by kaysond** [comment]
Yeah that's the expected behavior for an incorrect password. You should wrap a try/catch statement around the constructor call and handle the bad login in the catch.

**Comment by causefx** [comment]
Hi, I rewrote the bottom part of the constructor it now handles all exceptions perfectly.  I will submit a PR for you to test on your end....

```
	public function __construct($host, $password)
	{
		$this->url = $host . (substr($host, -1) == "/" ? "" : "/") . "json";
		$this->request_id = 0;
		$this->ch = curl_init($this->url);
		$curl_options = array(
			CURLOPT_RETURNTRANSFER => true,
			CURLOPT_HTTPHEADER => array("Accept: application/json", "Content-Type: application/json"),
			CURLOPT_ENCODING => "",
			CURLOPT_COOKIEJAR => "",
			CURLOPT_CONNECTTIMEOUT => 10,
			CURLOPT_TIMEOUT => 10,
			CURLOPT_CAINFO => getCert(),
			CURLOPT_SSL_VERIFYHOST => localURL($host) ? 0 : 2,
			CURLOPT_SSL_VERIFYPEER => localURL($host) ? 0 : 2,
			//CURLOPT_SSL_VERIFYPEER => false, THIS IS INSECURE!! However, deluge appears not to send intermediate certificates, so it can be necessary. Use with caution!
		);
		curl_setopt_array($this->ch, $curl_options);
		//Log in and get cookies
		$result = $this->makeRequest("auth.login", array($password));
		if (gettype($result) == 'boolean' && $result !== true) {
			throw new Exception("Login failed");
		} elseif (gettype($result) == 'string') {
			throw new Exception($result);
		}
	}
```

Testing with:
```
				try {
					$deluge = new deluge($GLOBALS['delugeURL'], decrypt($GLOBALS['delugePassword']));
					$torrents = $deluge->getTorrents(null, 'comment, download_payload_rate, eta, hash, is_finished, is_seed, message, name, paused, progress, queue, state, total_size, upload_payload_rate');
					return true;
				} catch (Exception $e) {
					return $e->getMessage();
				}
```

**Comment by kaysond** [comment]
I'm going to improve the error handling a little bit to only throw a single exception. That way `$e->getMessage()` is a complete response itself.

I didn't notice this at first, but the reason your original code didn't work is because you misspelled `Exception` ;)

**Comment by causefx** [comment]
yea i noticed that towards the end lol
